# Enables /season claim command for this server.
# This command will allow players to claim rewards
# from previous seasons. If you're using MySQL, then
# the rewards can be claimed on any server running this
# plugin when this is enabled.
claimingEnabled: true # Default | true

# This enables the tracking of player actions and
# statistics. If you disable this, the plugin will
# not act as a seasonal server. It will only allow
# players to claim rewards from previous seasons
# if claimingEnabled is set to true. Otherwise,
# the plugin will not do anything.

# --------------------- WARNING ----------------------
# This setting is critical to the function of the plugin.
# ONLY enable it on a server that you want to be a seasonal server.
# For example, if you want your rewards to go to a survival server,
# from a hardcore server, then you should disable this setting on
# the survival server, and enable it on the hardcore server.
# This setting has destructive capabilities, and can delete
# player inventories, end-chests, and worlds while enabled.
trackingEnabled: true # Default | true

# Disabling this will delete previous worlds
# when the season ends. It will not delete the
# rewards or database entries. It's useful to
# save space on your server, as well as to
# enable the option to spectate the previous
# season's world, or convert to a non-seasonal
# world.
persistSeasonWorlds: true # Default | true

# This is the minimum length for the season.
# Season cannot end before this length of time
# unless there are no players alive.
minSeasonLength: 14 #Default | 14

# This is the maximum length for the season.
# Season will end if it reaches this length of time.
# Rewards will be distributed among all players,
# based on maxSurvivorsRemaining and player activity.
maxSeasonLength: -1 # Default | -1 (Disabled)

# If the minSeasonLength is reached, and the player
# count is less than or equal to this value, it will
# trigger a vote to end the season. If the vote passes,
# the season will end and rewards will be distributed.
maxSurvivorsRemaining: 1 # Default | 1

# This is the minimum % of votes required to end the season.
# It will only apply if the maxSurvivorsRemaining condition is met.
minVotesToEndSeason: 50 # Default | 50 (%)

# The lastLoginThreshold is the number of days a player
# must be inactive before they are considered to have
# fallen off due to inactivity. If a player falls off,
# they will not be eligible for rewards, and their
# vote will not be counted.
lastLoginThreshold: 3 # Default | 3 (Days)

# This is the interval that Hardcore Seasons
# will notify players to vote to end the season,
# or to continue the season whenever minSeasonLength
# and maxSurvivorsRemaining conditions are met.
confirmationIntervalDays: 0 # Default | 0 (Days)
confirmationIntervalHours: 24 # Default | 24 (Hours)
confirmationIntervalMinutes: 0 # Default | 0 (Minutes)

# These commands will be executed when the season ends.
# The commands will only be executed on the non-seasonal server.
endOfSeasonCommands:
  - "say Season has ended! The world will be reset and rewards will be split among all players."
  - "server [playerName] survival"

# The storageType can be either SQLite or MySQL.
# SQLite will ignore the seasonalServer setting.
# You can manually move the db file to another server
# if you want to share the rewards across multiple servers.
storageType: "SQLite" # Default | SQLite

# If you're using MySQL, you must set the storageType to MySQL.
# The plugin will create the tables for you.
# If you're using SQLite, you can ignore these settings.
MySQL:
  host: 0.0.0.0
  port: 3306
  database: 'HCSeasons'
  username: ''
  password: ''
  # Determines the frequency for which the plugin will update the database.
  # Setting this to a lower value will only impact server performance slightly.
  # Most operations that this adjusts, are done asynchronously, and are not
  # critical to the function of the plugin.
  updateInterval: 5 # Default | 5 (Minutes)