name: HardcoreSeasons
version: ${project.version}
main: usa.mkaulfers.hardcoreseasons.HardcoreSeasons
api-version: "1.20"
commands:
  hardcoreseasons:
    usage: /<command> [reload|vote]
    description: HardcoreSeasons command
    aliases: [hcs]